#!/bin/bash  only for syntax highlight :)
# WARNING - all comments except in the first line must start with separated '#'

{
	node_type      = solid
	color          = (255, 255, 255)
}
{
	node_type      = solid
	color          = (200, 200, 200)
}

{
	node_type      = fluid
	color          = (0, 0, 0)
}
{
	node_type      = fluid
	color          = (50, 50, 50)
}

# moving wall
{
	node_type      = velocity
	velocity       = (0.001, 0, 0)
	pressure       = 0
	color          = (255, 0, 0)
}

