#!/bin/ruby  # only for syntax highlight in vim :)

#
#	Simulation settings
#

 collision_model = MRT            ; # MRT BGK
 fluid_model     = quasi_compressible ; # incompressible quasi_compressible
 data_type       = double         ; # single double
 lattice         = D3Q19          ;
 computational_engine = GPU ;


# Options used during automated surroundig of fluid and during automated node
# classification.
# All below options accept all node types and placement modifiers.
# However, I am not sure if it is reasonable to use boundary nodes of 
# type fluid/solid...
defaultWallNode                    = velocity_0 ;  
defaultExternalCornerNode          = velocity_0 external_corner ;   
defaultInternalCornerNode          = fluid ;   
defaultExternalEdgeNode            = velocity_0 external_edge ;   
defaultInternalEdgeNode            = velocity_0 internal_edge ;   
defaultNotIdentifiedNode           = bounce_back_2 ;   
defaultExternalEdgePressureNode    = velocity_0 external_edge_pressure_tangential ;   
defaultExternalCornerPressureNode  = velocity_0 external_corner_pressure_tangential ; 
defaultEdgeToPerpendicularWallNode = velocity_0 corner_on_edge_and_perpendicular_plane ;   


#
#	Predefined variables:  Nx  Ny  l_n
#


# velocity_residual_error = 1.0e-6 ;
err = 1.0 ; # Warunek zakonczenia obliczen - blad wzgledny sredniej predkosci dla kolejnych krokow


# Parametry obliczen warunkujace stabilnosc symulacji
#if collision_model == BGK #TODO: multiline expressions
	tau = 0.6 ; # tau > 0.5, minimalne wartosci (0.525 MRT, 0.58 BGK),
					  	# wieksza wart. tau zwieksza szybkosc obliczen w jednorodnych 
							# przestrzeniach, o ile uLB_maks nie przekracza nigdzie 0.2
					  	# dla zlozonych dziedzin tau=0.6 daje dobre wyniki, 
							# uLB_maks (0.001 - 0.005)
#elsif MRT == collision_model
#	tau = 0.6 ;
#end

# Parametry fizyczne symulacji
nu_phys   = 1.0e-6 ; # Fizyczna lepkosc kinematyczna plynu [m^2/s]
rho0_phys = 1000.0 ; # Gestosc fizyczna plynu [kg/m3]

# Wartosci charakterystyczne
# LB_characteristic_length
l_ch_LB = l_n - 1 ; # Dlugosc charakterystyczna (wysokosc kanalu) LB [Lu] gdy 
								  # zastosuje sie BB 2 (okalajace) -1
#l_ch_LB = (l_n)	# Dlugosc charakterystyczna (np. wysokosc kanalu) LB [Lu] gdy 
									# zastosuje sie war. velocity=0 na scianach +-0

# physical_characteristic_length
l_ch_phys = 0.00003 ; # Fizyczna dlugosc charakterystyczna [m]

# physical_characteristic_velocity
u_ch_phys = 0.01    ; # Predkosc charakterystyczna fizyczna [m/s]


rho0_LB = 1.0 ; #Poczatkowa gestosc LB (cisnienie)
ux0_LB = 0 ;
uy0_LB = 0 ;
